# Generated by Django 5.0.1 on 2024-02-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertySpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Specification",
                "verbose_name_plural": "Property Specifications",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        unique=True,
                        verbose_name="Property Name",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Property Type",
                "verbose_name_plural": "Property Types",
            },
        ),
        migrations.RemoveField(
            model_name="productspecificationvalue",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="productspecificationvalue",
            name="specification",
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="description"
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "The price must be between 0 and 999.99."
                            }
                        },
                        help_text="Maximum 999.99",
                        max_digits=5,
                        verbose_name="Regular price",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "The price must be between 0 and 999.99."
                            }
                        },
                        help_text="Maximum 999.99",
                        max_digits=5,
                        verbose_name="Discount price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Change Property visibility",
                        verbose_name="Property visibility",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="store.category",
                    ),
                ),
                (
                    "Property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="store.propertytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Propertys",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/default.png",
                        help_text="Upload a Property image",
                        upload_to="properties/",
                        verbose_name="image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Please add alturnative text",
                        max_length=255,
                        null=True,
                        verbose_name="Alturnative text",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Property_image",
                        to="store.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
            },
        ),
        migrations.CreateModel(
            name="PropertySpecificationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Property specification value (maximum of 255 words",
                        max_length=255,
                        verbose_name="value",
                    ),
                ),
                (
                    "Property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.property"
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="store.propertyspecification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Specification Value",
                "verbose_name_plural": "Property Specification Values",
            },
        ),
        migrations.AddField(
            model_name="propertyspecification",
            name="Property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="store.propertytype"
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.DeleteModel(
            name="ProductSpecification",
        ),
        migrations.DeleteModel(
            name="ProductSpecificationValue",
        ),
    ]
